version: '3.8'
services:
  mysql-db:
    build:
      context: .
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: EcomerceDb
    command: ["mysqld"]
